[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "multi-omics-factor-analysis-mofa"
version = "2.0.0"
description = "MOFA-Integrator: Multi-Omics Factor Analysis & Variance Decomposition Engine"
readme = "README.md"
authors = [{ name = "Dr. Abu Suraih Sakhri", email = "abusuraih@example.com" }]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Security/Cryptography",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
multi-omics-factor-analysis-mofa = "mofa_integrator.cli:main"

[project.urls]
Homepage = "https://github.com/abusuraihsakhri/multi-omics-factor-analysis-mofa"
Repository = "https://github.com/abusuraihsakhri/multi-omics-factor-analysis-mofa.git"
